
import "./globals.css";
// import"./entry.73168167.css";
import Script from 'next/script'

import Link from "next/link";

export const metadata = {
  title: "Desire",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
  
  <Link rel="shortcut icon" href="assets/img/logo/favicon.png" />
  <Link rel="stylesheet" href="assets/css/magnific-popup.css" />
  <Link rel="stylesheet" href="assets/css/swiper-bundle.min.css" />
  <Link rel="stylesheet" href="assets/css/aos.css" />
  <Link rel="stylesheet" href="../../../../cdn.jsdelivr.net/npm/bootstrap-icons%401.10.2/font/bootstrap-icons.css"
    crossorigin="anonymous" />
  <Link href="assets/css/style.css" rel="stylesheet" />
      <body>{children}
      <Script src="https://cdn.tailwindcss.com/" id="1"></Script>
       <Script src="assets/js/tailwindCongfig.js" id="2"></Script>
       <Script src="assets/js/jquery-3.7.0.min.js" id="3"></Script>
  <Script src="assets/js/swiper-bundle.min.js" id="4"></Script>

  <Script src="assets/js/jquery.magnific-popup.min.js" id="5"></Script>
  <Script src="assets/js/aos.js" id="6"></Script>

  <Script src="assets/js/index.js" id="7"></Script>
  <Script src="assets/js/main.js" id="8"></Script>
      </body>
    </html>
  );
}
